name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different (e.g., 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version to use

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Set Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Deploy to GitHub Pages
      run: |
        # Set up the remote to use the GITHUB_TOKEN for authentication
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npm run deploy

